language: python
python:
  - "3.6"

install:
  - pip install --only-binary=numpy,scipy,pandas numpy scipy pandas pytest pytest-cov codecov --quiet
  
  # install TensorFlow (CPU version).
  - pip install tensorflow==1.12.0 --quiet
  
  # install PyTorch (CPU version).
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl --quiet
  
  # install other setup extensions.
  - python setup.py install

script:
  - pytest --cov=./

branches:
  only:
  - master

after_success:
  - codecov || echo "codecov failed"
