language: python
python:
  - "3.6"

install:
  - pip install --only-binary=numpy,scipy,pandas numpy scipy pandas h5py pytest pytest-cov codecov --progress-bar off
  
  # install TensorFlow (CPU version).
  - pip install tensorflow==1.12.0 --progress-bar off
  
  # install PyTorch (CPU version).
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl --progress-bar off
  
  # install other setup extensions.
  - python setup.py install

script:
  # create dataset directory to avoid concurrent directory creation at runtime
  - mkdir ~/.cornac/datasets
  - pytest --cov=./

branches:
  only:
  - master

after_success:
  - codecov || echo "codecov failed"
