sudo: required
language: python

matrix:
  include:
    - os: linux
      env: DISTRIB="trusty" PYTHON_VERSION="3.6"
    - os: linux
      env: DISTRIB="trusty" PYTHON_VERSION="3.7"
    - os: osx
      language: generic
      env: DISTRIB="conda" PYTHON_VERSION="3.6"
    - os: osx
      language: generic
      env: DISTRIB="conda" PYTHON_VERSION="3.7"

install:  
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; 
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; 
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a
  - travis_retry conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment
  - travis_retry pip install --only-binary=numpy,scipy numpy scipy pytest --quiet
  - pip install -e .[tests]

script: python -m pytest --cov=cornac

deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDA1NTBkYzljLTM5MjgtNGU3MC05YmE3LThjYzk5ZDE5Mjk1YgACN3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJjb3JuYWMiXX0sICJ2ZXJzaW9uIjogMX0AAAYgCXMRUx_ujB5Fm2qQKqEMQf-q-AQxU3Z_kHddt4nJU0w"
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
