language: python
python:
  - "3.6"

install:
  - "pip install -r requirements_ci.txt"
  - "pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl"

script:
  - pytest --cov=./

branches:
  only:
  - master

after_success:
  - codecov || echo "codecov failed"
