build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
      PYTHON_ARCH: "64"

matrix:
    fast_finish: true

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy pandas pytest"
  - activate test-environment
  - python -m pip install --upgrade pip
  
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  
  # Install TensorFlow CPU version.
  - conda install tensorflow -c conda-forge 
  # Install PyTorch CPU version.
  - conda install pytorch-cpu -c pytorch
  - python setup.py install

test_script:
  - python -m pytest

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*