build: false

environment:
  matrix:
    - MINICONDA: C:\Miniconda35-x64
    - MINICONDA: C:\Miniconda36-x64

matrix:
    fast_finish: true

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - python -m pip install --upgrade pip
  - pip install numpy scipy pandas pytest
  # Install TensorFlow CPU version.
  - pip install tensorflow==1.12.0
  # Install PyTorch CPU version.
  - travis_retry conda install pytorch-cpu -c pytorch
  - python setup.py install

test_script:
  - python -m pytest

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*