# Configuration of py.test
[pytest]
norecursedirs = tests/cornac/datasets
pythonpath = .

addopts=-v
        --durations=20
        --ignore=tests/cornac/utils/test_download.py
        --ignore=tests/cornac/eval_methods/test_propensity_stratified_evaluation.py

