name: Release Drafter

on:
  push:
    tags:        
      - '*'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v5.25.0
        id: release_drafter
        with:
          config-name: workflows/release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
